package ggt.StarterPackage;

/**
* ggt/StarterPackage/exInvalidCountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufabe2.idl
* Mittwoch, 23. April 2014 10:48 Uhr MESZ
*/

public final class exInvalidCountHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.StarterPackage.exInvalidCount value = null;

  public exInvalidCountHolder ()
  {
  }

  public exInvalidCountHolder (ggt.StarterPackage.exInvalidCount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.StarterPackage.exInvalidCountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.StarterPackage.exInvalidCountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.StarterPackage.exInvalidCountHelper.type ();
  }

}
