package ggt;


/**
* ggt/KoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufabe2.idl
* Mittwoch, 23. April 2014 10:48 Uhr MESZ
*/

public interface KoordinatorOperations 
{

  // Methods for the Process
  void registerProcess (ggt.Process process) throws ggt.KoordinatorPackage.exAlreadyExists;
  boolean terminationComplete (ggt.Process terminator, int result);

  // Methods for the Starter
  void activateStarter (ggt.Starter starter, String starterName) throws ggt.KoordinatorPackage.exAlreadyExists;
  void deleteStarter (ggt.Starter starter);

  // Methods for the Client
  void startCalculation (int minProcesses, int maxProcesses, int minDelay, int maxDelay, int timeout, int ggt);
  ggt.Starter[] getStarterListe ();
  void quit ();
} // interface KoordinatorOperations
