package ggt;


/**
* ggt/Process.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Donnerstag, 24. April 2014 13:47 Uhr MESZ
*/

public interface Process extends ProcessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Process
