package ggt;


/**
* ggt/ProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Donnerstag, 24. April 2014 16:14 Uhr MESZ
*/

public interface ProcessOperations 
{
  String name ();

  // Methods for the other Processes
  void newNumber (int number, String senderName);
  void sendMarker (String terminator, int seqN);
  void stop (ggt.Process stopper);

  //Methods for the Starter
  void quit (String starterName);

  //Methods for the Koordinator
  void init (ggt.Process rightNeighbor, ggt.Process leftNeighbor, int startGGT, int delay, int timeout, monitor.Monitor theMonitor, ggt.Koordinator koor);
  void startCalulation ();
} // interface ProcessOperations
