package ggt;


/**
* ggt/ProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufabe2.idl
* Mittwoch, 23. April 2014 10:48 Uhr MESZ
*/

public interface ProcessOperations 
{
  String name ();

  // Methods for the other Processes
  void getNumber (int number);
  void terminate (ggt.Process terminator);
  void stop (ggt.Process stopper);

  //Methods for the Starter
  void quit (String starterName);

  //Methods for the Koordinator
  void init (ggt.Process rightNeighbor, ggt.Process leftNeighbor, int startGGT, int delay, int timeout, monitor.Monitor theMonitor, ggt.Koordinator koor);
  void startCalulation ();
} // interface ProcessOperations
