package ggt;


/**
* ggt/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufabe2.idl
* Mittwoch, 23. April 2014 10:48 Uhr MESZ
*/

public interface StarterOperations 
{
  String name ();

  //Methods for the Koordinator
  void createProcess (int count) throws ggt.StarterPackage.exInvalidCount;
  void quit ();
} // interface StarterOperations
